# 100 numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
   

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.zeros((10, 10))
print(array.size * array.itemsize)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
import subprocess
subprocess.call(["python", "-c", "import numpy; numpy.info(numpy.add)"])


0

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.43216881 0.48882898 0.20405063]
  [0.87709256 0.12762538 0.0536112 ]
  [0.66325052 0.77753337 0.91709116]]

 [[0.19818974 0.64459309 0.90364428]
  [0.29935724 0.95414228 0.98767719]
  [0.0701259  0.47765507 0.14941888]]

 [[0.7624115  0.80716584 0.20717226]
  [0.77268298 0.32664249 0.29788513]
  [0.75878812 0.46879179 0.74945298]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
array = np.random.random((10, 10))
min_value = np.min(array)
max_value = np.max(array)
print("Minimum:", min_value)
print("Maximum:", max_value)

Minimum: 0.002197336925522042
Maximum: 0.9986350995140637


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Mean:", mean_value)

Mean: 0.6207761408342836


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
existing_array = np.ones((3, 3))
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)           # nan
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)       # False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)

[[0.06183097 1.         0.09338898 0.31339287 0.35206024]
 [0.54755713 0.09294738 0.12751293 0.49563142 0.38908531]
 [0.17358367 0.16059816 0.61160611 0.63603329 0.8019299 ]
 [0.99039633 0.32301388 0.37376891 0.07686936 0.76481046]
 [0.17701914 0.         0.73497696 0.52723737 0.27844529]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
result = np.dot(matrix1, matrix2)
print(result)

[[0.83673465 0.23557097]
 [1.20559004 0.61414992]
 [0.62759461 0.31548753]
 [0.68012636 0.58497079]
 [1.42418984 0.60574894]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[(array > 3) & (array < 8)] *= -1
print(array)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5), -1))  # Output: 10
from numpy import *
print(sum(range(5), -1))  # Output: 10

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.array([1, 2, 3])
print(Z**Z)  # Legal
print(2 << Z >> 2)  # Legal
print(Z < -Z)  # Legal
print(1j * Z)  # Legal
print(Z / 1 / 1)  # Legal
# print(Z < Z > Z)  # Illegal (ambiguous)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
print(np.array(0) / np.array(0))  # Output: nan
print(np.array(0) // np.array(0))  # Output: 0 (floored division)
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18472\509868088.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # Output: nan
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18472\509868088.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # Output: 0 (floored division)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18472\509868088.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
float_array = np.random.uniform(-5, 5, 10)
rounded_array = np.where(float_array < 0, np.floor(float_array), np.ceil(float_array))
print(rounded_array)

[-1.  5. -1. -4.  1. -5. -1.  5.  1. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
np.seterr(all='ignore')
# Your code here
np.seterr(all='warn')  # Reset warnings to default behavior

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [39]:
result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result) # no,False

False


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18472\1010175222.py:1: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [40]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-04
Today: 2023-09-05
Tomorrow: 2023-09-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
A = np.ones(3) * 1
B = np.ones(3) * 2
result = np.add(A, B, out=B)
result = np.negative(A, out=A)
result = np.multiply(A, B, out=A)
print(result)

[-3. -3. -3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [43]:
random_array = np.random.uniform(0, 10, 10)
integer_part_method1 = random_array.astype(int)
integer_part_method2 = np.floor(random_array)
integer_part_method3 = np.ceil(random_array)
integer_part_method4 = np.trunc(random_array)
print("Method 1:", integer_part_method1)
print("Method 2:", integer_part_method2)
print("Method 3:", integer_part_method3)
print("Method 4:", integer_part_method4)

Method 1: [3 6 4 0 6 2 2 9 9 4]
Method 2: [3. 6. 4. 0. 6. 2. 2. 9. 9. 4.]
Method 3: [ 4.  7.  5.  1.  7.  3.  3. 10. 10.  5.]
Method 4: [3. 6. 4. 0. 6. 2. 2. 9. 9. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
matrix = np.zeros((5, 5)) + np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [45]:
def generator_function():
    for i in range(10):
        yield i

array = np.fromiter(generator_function(), dtype=int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:
vector = np.linspace(0, 1, 12, endpoint=False)[1:-1]
print(vector)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [47]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.13930066 0.14776109 0.31058965 0.35545918 0.64527315 0.6743905
 0.74776212 0.77761907 0.81528901 0.83496385]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [48]:
small_array = np.arange(10)
sum_result = np.add.reduce(small_array)
print(sum_result)


45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [49]:
A = np.random.random(5)
B = np.random.random(5)
equal = np.array_equal(A, B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [135]:
immutable_array = np.arange(10)
immutable_array.flags.writeable = False
# Attempting to modify the array will raise an error
# immutable_array[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [51]:
cartesian_coordinates = np.random.random((10, 2))
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("Polar Coordinates (r, theta):")
print("r =", r)
print("theta =", theta)

Polar Coordinates (r, theta):
r = [1.28597012 1.26500865 0.89940937 1.0182372  0.34778733 0.90668895
 0.77145122 0.96083757 0.40784519 0.59654301]
theta = [0.79907509 0.86043997 0.87934606 0.7568156  0.03946823 1.37188039
 1.31242546 0.88653071 0.18960641 0.77793839]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [52]:
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
print(random_vector)

[0.54379988 0.01196068 0.71289694 0.         0.40594046 0.83813772
 0.04242998 0.23119628 0.08841804 0.37168989]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [53]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
xx, yy = np.meshgrid(x, y)
structured_array = np.zeros((5, 5), [('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = xx, yy
print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [54]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [55]:
for dtype in [np.int8, np.int32, np.int64]:
    print("Minimum for {}: {}".format(dtype, np.iinfo(dtype).min))
    print("Maximum for {}: {}".format(dtype, np.iinfo(dtype).max))
for dtype in [np.float32, np.float64]:
    print("Minimum for {}: {}".format(dtype, np.finfo(dtype).min))
    print("Maximum for {}: {}".format(dtype, np.finfo(dtype).max))

Minimum for <class 'numpy.int8'>: -128
Maximum for <class 'numpy.int8'>: 127
Minimum for <class 'numpy.int32'>: -2147483648
Maximum for <class 'numpy.int32'>: 2147483647
Minimum for <class 'numpy.int64'>: -9223372036854775808
Maximum for <class 'numpy.int64'>: 9223372036854775807
Minimum for <class 'numpy.float32'>: -3.4028234663852886e+38
Maximum for <class 'numpy.float32'>: 3.4028234663852886e+38
Minimum for <class 'numpy.float64'>: -1.7976931348623157e+308
Maximum for <class 'numpy.float64'>: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [56]:
np.set_printoptions(threshold=np.inf)  # Print all values
array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [57]:
vector = np.arange(100)
scalar = 42
closest_value = vector[(np.abs(vector - scalar)).argmin()]
print("Closest value to {} is {}".format(scalar, closest_value))

Closest value to 42 is 42


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [58]:
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
structured_array = np.zeros(1, dtype=dtype)
print(structured_array)

[((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [2]:
random_vector = np.random.rand(100, 2)
distances = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        distance = np.linalg.norm(random_vector[i] - random_vector[j])
        distances[i, j] = distance
print(distances)


[[0.         0.06130142 0.54782015 ... 0.23273456 0.06764255 0.61572406]
 [0.06130142 0.         0.53638437 ... 0.2122168  0.06737706 0.57731735]
 [0.54782015 0.53638437 0.         ... 0.73985961 0.48224406 0.2808172 ]
 ...
 [0.23273456 0.2122168  0.73985961 ... 0.         0.27787684 0.73559124]
 [0.06764255 0.06737706 0.48224406 ... 0.27787684 0.         0.55028036]
 [0.61572406 0.57731735 0.2808172  ... 0.73559124 0.55028036 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [60]:
float_array = np.random.uniform(0, 10, 10).astype(np.float32)
int_array = float_array.view(np.int32)
print(int_array)

[1073789320 1087001630 1074664304 1084808016 1068964263 1092228402
 1091213811 1091989979 1091057460 1091265874]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [134]:
from io import StringIO

file_content = '''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
'''

string = StringIO(file_content)
A = np.genfromtxt(string, delimiter=",", dtype=int, missing_values='', filling_values=0)

print(A)


[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [69]:
array = np.array([11, 22, 33, 44, 55])
for index, value in np.ndenumerate(array):
    print(index, value)

(0,) 11
(1,) 22
(2,) 33
(3,) 44
(4,) 55


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [70]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(gaussian_array)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [71]:
p = 3
array = np.zeros((5, 5))
np.put(array, np.random.choice(range(5*5), p, replace=False), 1)
print(array)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [63]:
matrix = np.random.rand(5, 5)
mean_of_rows = matrix.mean(axis=1, keepdims=True)
result = matrix - mean_of_rows
print(result)

[[ 0.48141957 -0.18704536 -0.43670404  0.33018976 -0.18785993]
 [ 0.0330013  -0.17880982  0.47739274 -0.09386813 -0.23771609]
 [ 0.42904374 -0.04463975 -0.456504    0.1466457  -0.07454569]
 [-0.23229302 -0.16453958 -0.17148139  0.30250422  0.26580978]
 [-0.01948509 -0.29316729 -0.00703371  0.54299091 -0.22330482]]


#### 59. How to sort an array by the nth column? (★★☆)

In [62]:
matrix = np.random.randint(0, 10, (5, 5))
n = 2  # Sort by the third column
sorted_matrix = matrix[matrix[:, n].argsort()]
print(sorted_matrix)

[[2 3 0 0 3]
 [7 4 1 2 1]
 [1 5 2 1 6]
 [2 0 6 7 8]
 [2 0 7 1 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [72]:
matrix = np.random.randint(0, 2, (5, 5))
has_null_columns = not np.any(matrix.sum(axis=0))
print(has_null_columns)

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [73]:
array = np.random.uniform(0, 1, 10)
given_value = 0.5
nearest_value = array[np.abs(array - given_value).argmin()]
print(nearest_value)

0.4090477164433257


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [74]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
iterator = np.nditer([A, B, None])
for x, y, z in iterator:
    z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [75]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="No Name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', 'No Name')

array = NamedArray(np.arange(10), "My Array")
print(array.name)

My Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [76]:
vector = np.ones(10)
indices = np.random.randint(0, len(vector), 20)
np.add.at(vector, indices, 1)
print(vector)

[6. 3. 4. 4. 4. 1. 4. 1. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [77]:
X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([1, 3, 9, 3, 4, 1])
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [78]:
w, h = 16, 16
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)

256


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [79]:
array = np.random.randint(0, 10, (3, 4, 2, 2))
sum_last_two_axes = array.sum(axis=(-2, -1))
print(sum_last_two_axes)

[[16 12 29 28]
 [22 20 28 13]
 [17 19 25 27]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [80]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8])
S = np.array([0, 0, 1, 1, 2, 2, 3, 3])
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)

[1.5 3.5 5.5 7.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [81]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)
print(diagonal)

[108  60  54]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [82]:
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) + (len(vector) - 1) * 3)
new_vector[::4] = vector
print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [83]:
array1 = np.random.random((5, 5, 3))
array2 = np.random.random((5, 5))
result = array1 * array2[:, :, np.newaxis]
print(result)

[[[4.66827044e-01 1.55993525e-01 1.94667971e-01]
  [2.42212597e-03 3.37297197e-01 3.02609413e-01]
  [8.55116314e-02 1.13265813e-01 1.68477135e-01]
  [5.20349027e-01 6.81561213e-01 1.20981907e-01]
  [8.76032638e-02 1.33932409e-02 1.00012674e-01]]

 [[5.30491228e-02 1.97049944e-02 4.23196477e-03]
  [6.08523887e-01 4.44635788e-01 4.63243244e-01]
  [6.47572408e-01 4.86221589e-01 2.19993608e-01]
  [3.07715680e-03 7.45567548e-04 2.83510713e-03]
  [1.32824017e-01 1.53546594e-01 8.72172345e-02]]

 [[2.84454558e-04 3.44563939e-02 3.54098210e-03]
  [2.82114641e-02 6.27464193e-01 3.24764560e-01]
  [1.44557562e-01 1.20589334e-01 4.19182248e-01]
  [1.03066716e-01 7.60331412e-02 1.24555227e-01]
  [1.16700557e-01 5.18534567e-03 1.27272321e-01]]

 [[1.94604598e-01 1.95900908e-01 4.32519706e-01]
  [6.37326775e-02 6.31111267e-02 1.30094087e-01]
  [1.56244586e-02 4.79950957e-03 5.56277432e-02]
  [7.25326808e-01 3.22433070e-01 7.00624473e-01]
  [4.67689612e-02 1.40763024e-02 9.91588078e-03]]

 [[1.6680754

#### 72. How to swap two rows of an array? (★★★)

In [84]:
matrix = np.random.randint(0, 10, (5, 5))
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[1 5 2 3 6]
 [6 4 3 3 9]
 [9 9 4 1 3]
 [4 4 3 0 9]
 [9 1 9 1 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [85]:
triangles = np.random.randint(0, 10, (10, 3))
edges = np.roll(triangles.repeat(2, axis=1), -1, axis=1)
edges = edges.reshape(len(edges) * 3, 2)
sorted_edges = np.sort(edges, axis=1)
unique_edges = np.unique(sorted_edges, axis=0)
print(unique_edges)


[[0 2]
 [0 3]
 [0 4]
 [1 2]
 [1 3]
 [1 5]
 [1 6]
 [1 8]
 [1 9]
 [2 3]
 [2 4]
 [2 5]
 [2 6]
 [2 8]
 [3 4]
 [3 6]
 [3 8]
 [4 8]
 [5 8]
 [5 9]
 [6 8]
 [8 9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [86]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [87]:
def moving_average(arr, window):
    return np.convolve(arr, np.ones(window), mode='valid') / window

array = np.arange(20)
window = 4
averages = moving_average(array, window)
print(averages)

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [89]:
Z = np.arange(10)
stride = 3
result = []

for i in range(len(Z) - stride + 1):
    result.append(Z[i:i+stride])

strided_array = np.array(result)
print(strided_array)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [90]:
boolean_array = np.array([True, False, True])
negated_boolean_array = np.logical_not(boolean_array)
print(negated_boolean_array)

float_array = np.array([-1.5, 2.0, -3.5])
np.negative(float_array, out=float_array)
print(float_array)

[False  True False]
[ 1.5 -2.   3.5]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [91]:
P0 = np.random.random((5, 2))
P1 = np.random.random((5, 2))
p = np.random.random(2)

def distance_to_line(P0, P1, p):
    return np.abs(np.cross(P1 - P0, p - P0) / np.linalg.norm(P1 - P0))

distances = distance_to_line(P0, P1, p)
print(distances)

[0.12063175 0.44586687 0.19971671 0.22093434 0.30031015]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [93]:


P0 = np.random.random((5, 2))
P1 = np.random.random((5, 2))
P = np.random.random((10, 2))

def distance_to_lines(P0, P1, P):
    num_lines = len(P0)
    num_points = len(P)
    distances = np.zeros((num_lines, num_points))
    
    for i in range(num_lines):
        line_start = P0[i]
        line_end = P1[i]
        
        for j in range(num_points):
            point = P[j]
            
            numerator = np.abs(np.cross(line_end - line_start, point - line_start))
            denominator = np.linalg.norm(line_end - line_start)
            
            distances[i, j] = numerator / denominator
    
    return distances

distances = distance_to_lines(P0, P1, P)
print(distances)


[[0.2590594  0.382097   0.00926625 0.19870821 0.45085572 0.57784825
  0.47534374 0.60800425 0.1846944  0.30423706]
 [0.08946716 0.4072326  0.42842571 0.04126055 0.09225342 0.1200352
  0.04723616 0.25674788 0.21648949 0.40903067]
 [0.26793516 0.29142244 0.09199655 0.15870358 0.45189769 0.54757103
  0.42702993 0.61752402 0.06809525 0.37039932]
 [0.42335263 0.73405366 0.48447414 0.07917285 0.55509397 0.12091889
  0.10368865 0.0434549  0.09585408 0.27104791]
 [0.29713531 0.08598872 0.13776067 0.09875587 0.39535968 0.1685401
  0.05158866 0.3029824  0.32974563 0.27571354]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [96]:
def extract_subpart(array, shape, center):
    pad_x, pad_y = [(s - 1) // 2 for s in shape]
    x, y = center
    subpart = array[x - pad_x : x + pad_x + 1, y - pad_y : y + pad_y + 1]
    return subpart

array = np.random.random((8, 8))
shape = (3, 3)
center = (4, 4)
subpart = extract_subpart(array, shape, center)
print(subpart)

[[0.3377822  0.94849785 0.7268433 ]
 [0.09533329 0.13912996 0.38738404]
 [0.60593407 0.66546898 0.392864  ]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [97]:
Z = np.arange(1, 15)
window = 4
R = np.lib.stride_tricks.sliding_window_view(Z, window)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [98]:
matrix = np.random.randint(0, 2, (4, 4))
rank = np.linalg.matrix_rank(matrix)
print(rank)

3


#### 83. How to find the most frequent value in an array?

In [99]:
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
most_frequent_value = np.bincount(array).argmax()
print(most_frequent_value)

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [100]:
matrix = np.random.randint(0, 10, (10, 10))
block_size = 3
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (block_size, block_size))
print(blocks)

[[[[6 0 8]
   [4 5 5]
   [2 0 8]]

  [[0 8 2]
   [5 5 1]
   [0 8 7]]

  [[8 2 1]
   [5 1 7]
   [8 7 9]]

  [[2 1 7]
   [1 7 7]
   [7 9 0]]

  [[1 7 1]
   [7 7 1]
   [9 0 9]]

  [[7 1 5]
   [7 1 8]
   [0 9 9]]

  [[1 5 4]
   [1 8 5]
   [9 9 6]]

  [[5 4 2]
   [8 5 8]
   [9 6 2]]]


 [[[4 5 5]
   [2 0 8]
   [5 9 4]]

  [[5 5 1]
   [0 8 7]
   [9 4 6]]

  [[5 1 7]
   [8 7 9]
   [4 6 1]]

  [[1 7 7]
   [7 9 0]
   [6 1 4]]

  [[7 7 1]
   [9 0 9]
   [1 4 0]]

  [[7 1 8]
   [0 9 9]
   [4 0 3]]

  [[1 8 5]
   [9 9 6]
   [0 3 6]]

  [[8 5 8]
   [9 6 2]
   [3 6 4]]]


 [[[2 0 8]
   [5 9 4]
   [5 0 3]]

  [[0 8 7]
   [9 4 6]
   [0 3 4]]

  [[8 7 9]
   [4 6 1]
   [3 4 2]]

  [[7 9 0]
   [6 1 4]
   [4 2 2]]

  [[9 0 9]
   [1 4 0]
   [2 2 3]]

  [[0 9 9]
   [4 0 3]
   [2 3 0]]

  [[9 9 6]
   [0 3 6]
   [3 0 5]]

  [[9 6 2]
   [3 6 4]
   [0 5 4]]]


 [[[5 9 4]
   [5 0 3]
   [0 8 2]]

  [[9 4 6]
   [0 3 4]
   [8 2 9]]

  [[4 6 1]
   [3 4 2]
   [2 9 7]]

  [[6 1 4]
   [4 2 2]
   [9 7 5]]

  [[1 4 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [101]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, key, value):
        i, j = key
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

shape = (4, 4)
symmetric_array = np.zeros(shape).view(SymmetricArray)
symmetric_array[1, 2] = 42
print(symmetric_array)
print(symmetric_array[2, 1])

[[ 0.  0.  0.  0.]
 [ 0.  0. 42.  0.]
 [ 0. 42.  0.  0.]
 [ 0.  0.  0.  0.]]
42.0


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [102]:
p = 5
n = 3
matrices = np.random.random((p, n, n))
vectors = np.random.random((p, n, 1))
result = np.sum(matrices @ vectors, axis=0)
print(result)

[[3.87782766]
 [4.40422662]
 [5.07178281]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [103]:
array = np.random.randint(0, 10, (16, 16))
block_size = (4, 4)
block_sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], block_size[0]), axis=0), np.arange(0, array.shape[1], block_size[1]), axis=1)
print(block_sum)

[[89 72 79 58]
 [63 74 72 62]
 [85 77 74 69]
 [70 80 68 80]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [104]:
def game_of_life(grid, iterations):
    def count_neighbors(arr, i, j):
        neighbors = arr[i-1:i+2, j-1:j+2]
        neighbors_sum = np.sum(neighbors) - arr[i, j]
        return neighbors_sum

    for _ in range(iterations):
        new_grid = grid.copy()
        for i in range(1, grid.shape[0]-1):
            for j in range(1, grid.shape[1]-1):
                neighbors_count = count_neighbors(grid, i, j)
                if grid[i, j] == 1:
                    if neighbors_count < 2 or neighbors_count > 3:
                        new_grid[i, j] = 0
                else:
                    if neighbors_count == 3:
                        new_grid[i, j] = 1
        grid = new_grid
    return grid

initial_state = np.random.choice([0, 1], size=(10, 10))
final_state = game_of_life(initial_state, iterations=5)
print(final_state)

[[0 1 0 0 0 0 1 1 1 0]
 [1 0 0 0 1 1 0 1 0 1]
 [0 0 0 0 1 1 0 0 0 1]
 [1 0 0 0 1 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [0 0 1 1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 1 0 0 0 0 1]]


#### 89. How to get the n largest values of an array (★★★)

In [105]:
array = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])
n_largest = array[np.argsort(array)[-3:]]
print(n_largest)


[7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [106]:
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print(cartesian_product)

[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [107]:
array = np.array([("Alice", 25, 1.75), ("Bob", 30, 1.80), ("Charlie", 35, 1.90)], dtype=[("name", 'U10'), ("age", int), ("height", float)])
record_array = np.rec.array(array)
print(record_array)

[('Alice', 25, 1.75) ('Bob', 30, 1.8 ) ('Charlie', 35, 1.9 )]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [111]:
Z = np.random.random(1000000)
method1 = Z * Z * Z
method2 = np.power(Z, 3)
method3 = np.einsum('i,i,i->i', Z, Z, Z)
print(np.allclose(method1, method2))
print(np.allclose(method1, method3))

True
True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [123]:

A = np.array([[1, 2, 3],
              [2, 3, 4],
              [3, 4, 5],
              [4, 5, 6],
              [5, 6, 7],
              [6, 7, 8],
              [7, 8, 9],
              [8, 9, 10]])

B = np.array([[3, 2],
              [5, 6]])

sorted_unique_B = np.vstack([tuple(sorted(row)) for row in B])

mask = np.zeros(A.shape[0], dtype=bool)


for i, row in enumerate(A):
    for b_row in sorted_unique_B:
        if set(b_row).issubset(row):
            mask[i] = True
            break  
result = A[mask]

print(result)


[[1 2 3]
 [2 3 4]
 [4 5 6]
 [5 6 7]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [114]:
matrix = np.random.randint(0, 5, (10, 3))
unequal_rows = matrix[~np.all(matrix[:, 1:] == matrix[:, :-1], axis=1)]
print(unequal_rows)

[[3 0 3]
 [0 1 3]
 [4 0 1]
 [4 4 0]
 [0 4 1]
 [1 3 0]
 [3 0 2]
 [0 0 2]
 [4 1 4]
 [3 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [115]:
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.uint8)
matrix = np.unpackbits(vector[:, np.newaxis], axis=1)
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [116]:
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])
unique_rows = np.unique(array, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [117]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_product = np.einsum("i,i->", A, B)
outer_product = np.einsum("i,j->ij", A, B)
sum_product = np.einsum("i->", A)
elementwise_product = np.einsum("i,i->i", A, B)
print("Inner Product:", inner_product)
print("Outer Product:\n", outer_product)
print("Sum:", sum_product)
print("Elementwise Product:", elementwise_product)

Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: 6
Elementwise Product: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [118]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 3, 5, 7, 11])
num_samples = 10
sampled_indices = np.linspace(0, len(X) - 1, num_samples, dtype=int)
sampled_path = (X[sampled_indices], Y[sampled_indices])
print(sampled_path)

(array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5]), array([ 2,  2,  2,  3,  3,  5,  5,  7,  7, 11]))


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [131]:

n = 6
X = np.array([[1, 2, 3], [4, 1, 1], [2, 2, 2], [0, 3, 3], [6, 0, 0]])

rows_meeting_criteria = X[(np.all(X % 1 == 0, axis=1)) & (np.sum(X, axis=1) == n)]

print(rows_meeting_criteria)


[[1 2 3]
 [4 1 1]
 [2 2 2]
 [0 3 3]
 [6 0 0]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [120]:
X = np.random.randn(1000)  # Example data
N = 10000  
bootstrap_samples = np.random.choice(X, (N, len(X)), replace=True)
bootstrap_means = bootstrap_samples.mean(axis=1)
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])
print("95% Confidence Interval for Mean:", confidence_interval)

95% Confidence Interval for Mean: [-0.07555291  0.05241579]
